// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class BondoraDbV8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BondoraDbV8));
        
        string IMigrationMetadata.Id
        {
            get { return "201902241346174_BondoraDb-V8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
